# ===== SQL Server connection =====
db.url=jdbc:sqlserver://localhost:1433;databaseName=FastFoodPreorder;encrypt=true;trustServerCertificate=true
db.username=sa
db.password=FastFood@123
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===== HikariCP pool =====
db.pool.maximumPoolSize=20
db.pool.minimumIdle=5
db.pool.connectionTimeout=30000
db.pool.idleTimeout=600000
